In [ ]:
import cv2

im = cv2.imread('meter1854.jpg')

print(type(im))
# <class 'numpy.ndarray'>

print(im.shape)
# (225, 400, 3)

print(im.dtype)
# uint8

<class 'numpy.ndarray'>
(4032, 3024, 3)
uint8


In [ ]:
cv2.imwrite('meter1854.jpg', im)

True

In [ ]:
import numpy as np
from PIL import Image

im = np.array(Image.open('meter1854.jpg').convert('L').resize((256, 256)))
print(type(im))

<class 'numpy.ndarray'>


In [ ]:
th = 128
im_bool = im > th
print(im_bool)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [ ]:
im_bin_128 = (im > th) * 255
print(im_bin_128)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
im_bin_64 = (im > 64) * 255
im_bin_192 = (im > 192) * 255

im_bin = np.concatenate((im_bin_64, im_bin_128, im_bin_192), axis=1)
Image.fromarray(np.uint8(im_bin)).save('meter1854.jpg')